// Generated by tools/gen_service_vectors.py -- do not edit by hand.
// Golden vectors produced by the reference implementation, tools/bmc_manage.py.
// Regenerate with: python tools/gen_service_vectors.py > tests/service_vectors.hpp
#pragma once
#include "bmc/service.hpp"
#include <string>
#include <utility>
#include <vector>
// Generated by tools/gen_service_vectors.py -- do not edit by hand.
// Vector of (path, expected JSON body); an empty body means the reference returns 404.
const std::vector<std::pair<std::string, std::string>> kResourceVectors = {
    {"/redfish/v1/", "{\"@odata.id\": \"/redfish/v1/\", \"Id\": \"RootService\", \"Name\": \"BMC-Lite management\", \"Managers\": {\"@odata.id\": \"/redfish/v1/Managers\"}}"},
    {"/redfish/v1/Managers", "{\"@odata.id\": \"/redfish/v1/Managers\", \"Members@odata.count\": 1, \"Members\": [{\"@odata.id\": \"/redfish/v1/Managers/BMC\"}]}"},
    {"/redfish/v1/Managers/BMC", "{\"@odata.id\": \"/redfish/v1/Managers/BMC\", \"Id\": \"BMC\", \"Name\": \"BMC-Lite\", \"LogServices\": {\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices\"}}"},
    {"/redfish/v1/Managers/BMC/LogServices", "{\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices\", \"Members@odata.count\": 1, \"Members\": [{\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL\"}]}"},
    {"/redfish/v1/Managers/BMC/LogServices/SEL", "{\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL\", \"Id\": \"SEL\", \"Name\": \"System event log\", \"Entries\": {\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries\"}}"},
    {"/redfish/v1/Managers/BMC/LogServices/SEL/Entries", "{\"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries\", \"Members@odata.count\": 6, \"Members\": [{\"Id\": \"1\", \"TimestampMilliseconds\": 1700000000000, \"Sensor\": \"cpu\", \"State\": \"normal\", \"Message\": \"state change: normal -> normal\", \"Value\": 41.5, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/1\"}, {\"Id\": \"2\", \"TimestampMilliseconds\": 1700000001500, \"Sensor\": \"cpu\", \"State\": \"critical\", \"Message\": \"state change: normal -> critical\", \"Value\": 95, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/2\"}, {\"Id\": \"3\", \"TimestampMilliseconds\": 1700000002500, \"Sensor\": \"cpu\", \"State\": \"critical\", \"Message\": \"state change: critical -> critical\", \"Value\": 96.25, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/3\"}, {\"Id\": \"4\", \"TimestampMilliseconds\": 1700000003500, \"Sensor\": \"fan1\", \"State\": \"warning\", \"Message\": \"state change: normal -> warning\", \"Value\": null, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/4\"}, {\"Id\": \"5\", \"TimestampMilliseconds\": 1700000004500, \"Sensor\": \"rule\", \"State\": \"active\", \"Message\": \"critical cooling\", \"Value\": null, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/5\"}, {\"Id\": \"10\", \"TimestampMilliseconds\": 1700000005500, \"Sensor\": \"odd\\\"sensor\", \"State\": \"unavailable\", \"Message\": \"probe failed\", \"Value\": 0.125, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/10\"}]}"},
    {"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/2", "{\"Id\": \"2\", \"TimestampMilliseconds\": 1700000001500, \"Sensor\": \"cpu\", \"State\": \"critical\", \"Message\": \"state change: normal -> critical\", \"Value\": 95, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/2\"}"},
    {"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/5", "{\"Id\": \"5\", \"TimestampMilliseconds\": 1700000004500, \"Sensor\": \"rule\", \"State\": \"active\", \"Message\": \"critical cooling\", \"Value\": null, \"@odata.id\": \"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/5\"}"},
    {"/redfish/v1/Managers/BMC/LogServices/SEL/Entries/999", ""},
    {"/redfish/v1/nope", ""},
};

// Expected /metrics body.
const std::string kMetricsVector = "# HELP bmc_sel_records Number of readable records in the SEL file.\n# TYPE bmc_sel_records gauge\nbmc_sel_records 6\n# HELP bmc_sel_last_id Highest readable SEL record identifier.\n# TYPE bmc_sel_last_id gauge\nbmc_sel_last_id 10\n# HELP bmc_sensor_state Last recorded sensor state; exactly one state is 1.\n# TYPE bmc_sensor_state gauge\nbmc_sensor_state{sensor=\"cpu\",state=\"normal\"} 0\nbmc_sensor_state{sensor=\"cpu\",state=\"warning\"} 0\nbmc_sensor_state{sensor=\"cpu\",state=\"critical\"} 1\nbmc_sensor_state{sensor=\"cpu\",state=\"unavailable\"} 0\nbmc_sensor_state{sensor=\"fan1\",state=\"normal\"} 0\nbmc_sensor_state{sensor=\"fan1\",state=\"warning\"} 1\nbmc_sensor_state{sensor=\"fan1\",state=\"critical\"} 0\nbmc_sensor_state{sensor=\"fan1\",state=\"unavailable\"} 0\nbmc_sensor_state{sensor=\"odd\\\"sensor\",state=\"normal\"} 0\nbmc_sensor_state{sensor=\"odd\\\"sensor\",state=\"warning\"} 0\nbmc_sensor_state{sensor=\"odd\\\"sensor\",state=\"critical\"} 0\nbmc_sensor_state{sensor=\"odd\\\"sensor\",state=\"unavailable\"} 1\n# HELP bmc_sensor_last_event_value Sensor value at its last recorded state change; not a live sample.\n# TYPE bmc_sensor_last_event_value gauge\nbmc_sensor_last_event_value{sensor=\"cpu\"} 96.25\nbmc_sensor_last_event_value{sensor=\"odd\\\"sensor\"} 0.125\n# HELP bmc_sensor_last_event_timestamp_seconds Timestamp of the last recorded state change.\n# TYPE bmc_sensor_last_event_timestamp_seconds gauge\nbmc_sensor_last_event_timestamp_seconds{sensor=\"cpu\"} 1700000002.5\nbmc_sensor_last_event_timestamp_seconds{sensor=\"fan1\"} 1700000003.5\nbmc_sensor_last_event_timestamp_seconds{sensor=\"odd\\\"sensor\"} 1700000005.5\n";

// The same records as C++ literals, so the test rebuilds the input independently
// of the JSON/plain-text parsing paths.
const std::vector<bmc::SelEntry> kVectorEntries = {
    {1, 1700000000000, "cpu", "normal", "state change: normal -> normal", 41.5},
    {2, 1700000001500, "cpu", "critical", "state change: normal -> critical", 95.0},
    {3, 1700000002500, "cpu", "critical", "state change: critical -> critical", 96.25},
    {4, 1700000003500, "fan1", "warning", "state change: normal -> warning", std::nullopt},
    {5, 1700000004500, "rule", "active", "critical cooling", std::nullopt},
    {10, 1700000005500, "odd\"sensor", "unavailable", "probe failed", 0.125},
};
