"""Generate golden vectors from the reference Python implementation.

Run from the repository root:

    python tools/gen_service_vectors.py

The output is a C++ initializer list that tests/core_test.cpp embeds, so the C++
read-only service is checked byte-for-byte against tools/bmc_manage.py.

本文件把参考实现 tools/bmc_manage.py 的响应固化成 C++ 向量，输出写到标准输出，
预期的用法是重定向进头文件：

    python tools/gen_service_vectors.py > tests/service_vectors.hpp

按路径导入 bmc_manage.py（而不是当包导入），保证对拍的就是仓库里的那一份实现。
注意 tests/service_vectors.hpp 的前 8 行（文件头三行说明、``#pragma once`` 与
``#include``）由人工维护，脚本从 kResourceVectors 开始输出，重定向后需自行补回。
"""
import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def load_manage():
    """按文件路径导入 tools/bmc_manage.py，返回已执行完的模块对象。

    :return: manage 模块；只定义函数，不读文件、不起服务。
    """
    # 用文件路径加载，不依赖当前工作目录或 sys.path 里可能存在的同名模块。
    spec = importlib.util.spec_from_file_location("manage", ROOT / "tools" / "bmc_manage.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# Entries that mirror what src/sel.cpp writes and exercises the interesting cases:
# a state change, a repeated state, a non-state record, a null value, an
# escaped sensor label, and a fractional value.
# 六条记录与上面列出的六类情况一一对应；Id 故意跳号（1..5 与 10），
# 使 bmc_sel_last_id(10) 不等于记录条数(6)，能发现“拿条数当 Id”的实现错误。
ENTRIES = [
    # 1：cpu 的首条状态记录，作为后续状态迁移的基线。
    {"Id": "1", "TimestampMilliseconds": 1700000000000, "Sensor": "cpu",
     "State": "normal", "Message": "state change: normal -> normal", "Value": 41.5},
    # 2：同一传感器发生状态变化（normal -> critical），事件值取最后一条。
    {"Id": "2", "TimestampMilliseconds": 1700000001500, "Sensor": "cpu",
     "State": "critical", "Message": "state change: normal -> critical", "Value": 95},
    # 3：重复状态（critical -> critical），验证 latest 取最后一条而非第一条。
    {"Id": "3", "TimestampMilliseconds": 1700000002500, "Sensor": "cpu",
     "State": "critical", "Message": "state change: critical -> critical", "Value": 96.25},
    # 4：值为 null，状态序列要输出，数值序列必须跳过该条。
    {"Id": "4", "TimestampMilliseconds": 1700000003500, "Sensor": "fan1",
     "State": "warning", "Message": "state change: normal -> warning", "Value": None},
    # 5：非状态记录（State=active 不属于四个状态名），不应产生任何指标。
    {"Id": "5", "TimestampMilliseconds": 1700000004500, "Sensor": "rule",
     "State": "active", "Message": "critical cooling", "Value": None},
    # 10：传感器名含双引号，覆盖标签转义；0.125 覆盖小数的事件值输出。
    {"Id": "10", "TimestampMilliseconds": 1700000005500, "Sensor": 'odd"sensor',
     "State": "unavailable", "Message": "probe failed", "Value": 0.125},
]

# 资源路径逐条对应 resource() 的分支；最后两条分别是不存在的 Id 与不存在的路径，
# 参考实现返回 None，输出里就是空 body。
PATHS = [
    "/redfish/v1/",
    "/redfish/v1/Managers",
    "/redfish/v1/Managers/BMC",
    "/redfish/v1/Managers/BMC/LogServices",
    "/redfish/v1/Managers/BMC/LogServices/SEL",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/2",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/5",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/999",
    "/redfish/v1/nope",
]


def cpp_string(text):
    """把 Python 字符串转成 C++ 双引号字面量。

    :param text: 任意字符串，可能含引号、反斜杠、换行或控制字符。
    :return: 带外层双引号、可直接写进 C++ 源码的字面量。
    """
    out = []
    for character in text:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif character == "\r":
            out.append("\\r")
        elif ord(character) < 0x20:
            # 其余 C0 控制字符用 \xNN 表示，避免生成跨行的字面量。
            out.append("\\x%02x" % ord(character))
        else:
            out.append(character)
    return '"' + "".join(out) + '"'


def main():
    """生成全部向量并打印到标准输出。

    :return: 固定返回 None；``sys.exit(main())`` 因此得到退出码 0。
    """
    manage = load_manage()
    # 复制一份交给 resource()/metrics()，两个函数都只读取它。
    entries = [dict(entry, Value=entry["Value"]) for entry in ENTRIES]
    print("// Generated by tools/gen_service_vectors.py -- do not edit by hand.")
    print("// Vector of (path, expected JSON body); an empty body means the reference returns 404.")
    print("const std::vector<std::pair<std::string, std::string>> kResourceVectors = {")
    for path in PATHS:
        body = manage.resource(path, entries)
        text = "" if body is None else json.dumps(body, allow_nan=False)
        print("    {%s, %s}," % (cpp_string(path), cpp_string(text)))
    print("};")
    print()
    print("// Expected /metrics body.")
    print("const std::string kMetricsVector = %s;" % cpp_string(manage.metrics(entries)))
    print()
    print("// The same records as C++ literals, so the test rebuilds the input independently")
    print("// of the JSON/plain-text parsing paths.")
    # 上面两行注释随输出一起进头文件；记录同时以 C++ 字面量再输出一遍，测试据此
    # 重建 SelEntry，不经过 JSON 或 SEL 文本解析，把“响应层格式”与“解析正确性”
    # 分开验证。
    print("const std::vector<bmc::SelEntry> kVectorEntries = {")
    for entry in ENTRIES:
        if entry["Value"] is None:
            # 缺失的事件值对应 bmc::SelEntry 的 std::nullopt。
            value = "std::nullopt"
        else:
            # repr 给出最短往返表示；整数结果补上 .0，保证 C++ 侧推导为 double。
            text = repr(float(entry["Value"]))
            value = text if "." in text or "e" in text else text + ".0"
        print("    {%d, %d, %s, %s, %s, %s}," % (
            int(entry["Id"]), entry["TimestampMilliseconds"], cpp_string(entry["Sensor"]),
            cpp_string(entry["State"]), cpp_string(entry["Message"]), value))
    print("};")


if __name__ == "__main__":
    sys.exit(main())
