"""Generate golden vectors from the reference Python implementation.

Run from the repository root:

    python tools/gen_service_vectors.py

The output is a C++ initializer list that tests/core_test.cpp embeds, so the C++
read-only service is checked byte-for-byte against tools/bmc_manage.py.
"""
import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def load_manage():
    spec = importlib.util.spec_from_file_location("manage", ROOT / "tools" / "bmc_manage.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# Entries that mirror what src/sel.cpp writes and exercises the interesting cases:
# a state change, a repeated state, a non-state record, a null value, an
# escaped sensor label, and a fractional value.
ENTRIES = [
    {"Id": "1", "TimestampMilliseconds": 1700000000000, "Sensor": "cpu",
     "State": "normal", "Message": "state change: normal -> normal", "Value": 41.5},
    {"Id": "2", "TimestampMilliseconds": 1700000001500, "Sensor": "cpu",
     "State": "critical", "Message": "state change: normal -> critical", "Value": 95},
    {"Id": "3", "TimestampMilliseconds": 1700000002500, "Sensor": "cpu",
     "State": "critical", "Message": "state change: critical -> critical", "Value": 96.25},
    {"Id": "4", "TimestampMilliseconds": 1700000003500, "Sensor": "fan1",
     "State": "warning", "Message": "state change: normal -> warning", "Value": None},
    {"Id": "5", "TimestampMilliseconds": 1700000004500, "Sensor": "rule",
     "State": "active", "Message": "critical cooling", "Value": None},
    {"Id": "10", "TimestampMilliseconds": 1700000005500, "Sensor": 'odd"sensor',
     "State": "unavailable", "Message": "probe failed", "Value": 0.125},
]

PATHS = [
    "/redfish/v1/",
    "/redfish/v1/Managers",
    "/redfish/v1/Managers/BMC",
    "/redfish/v1/Managers/BMC/LogServices",
    "/redfish/v1/Managers/BMC/LogServices/SEL",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/2",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/5",
    "/redfish/v1/Managers/BMC/LogServices/SEL/Entries/999",
    "/redfish/v1/nope",
]


def cpp_string(text):
    out = []
    for character in text:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif character == "\r":
            out.append("\\r")
        elif ord(character) < 0x20:
            out.append("\\x%02x" % ord(character))
        else:
            out.append(character)
    return '"' + "".join(out) + '"'


def main():
    manage = load_manage()
    entries = [dict(entry, Value=entry["Value"]) for entry in ENTRIES]
    print("// Generated by tools/gen_service_vectors.py -- do not edit by hand.")
    print("// Vector of (path, expected JSON body); an empty body means the reference returns 404.")
    print("const std::vector<std::pair<std::string, std::string>> kResourceVectors = {")
    for path in PATHS:
        body = manage.resource(path, entries)
        text = "" if body is None else json.dumps(body, allow_nan=False)
        print("    {%s, %s}," % (cpp_string(path), cpp_string(text)))
    print("};")
    print()
    print("// Expected /metrics body.")
    print("const std::string kMetricsVector = %s;" % cpp_string(manage.metrics(entries)))
    print()
    print("// The same records as C++ literals, so the test rebuilds the input independently")
    print("// of the JSON/plain-text parsing paths.")
    print("const std::vector<bmc::SelEntry> kVectorEntries = {")
    for entry in ENTRIES:
        if entry["Value"] is None:
            value = "std::nullopt"
        else:
            text = repr(float(entry["Value"]))
            value = text if "." in text or "e" in text else text + ".0"
        print("    {%d, %d, %s, %s, %s, %s}," % (
            int(entry["Id"]), entry["TimestampMilliseconds"], cpp_string(entry["Sensor"]),
            cpp_string(entry["State"]), cpp_string(entry["Message"]), value))
    print("};")


if __name__ == "__main__":
    sys.exit(main())
